#!/usr/bin/env python3
"""Generate src/vial_definition.h from vial.json (LZMA-compressed).

Vial GUI expects `keyboard_definition` returned by CMD_VIAL_GET_DEFINITION
to be the LZMA-compressed JSON definition (see vial-gui reload_layout:
`json.loads(lzma.decompress(payload))`). The firmware just stores the
pre-compressed bytes and serves them page-by-page; no runtime compression.
"""
import json
import lzma
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
JSON_PATH = os.path.join(ROOT, "vial.json")
OUT_PATH = os.path.join(ROOT, "src", "vial_definition.h")


def main():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        raw = f.read()
    # Validate JSON parses (mirror GUI side which json.loads after decompress)
    json.loads(raw)
    data = lzma.compress(
        raw.encode("utf-8"),
        format=lzma.FORMAT_ALONE,
        preset=9,
    )
    n = len(data)
    lines = []
    lines.append("/* Auto-generated by tools/gen_vial_def.py -- DO NOT EDIT */")
    lines.append("/* LZMA-compressed vial.json (Vial GUI keyboard definition). */")
    lines.append(f"/* Source: vial.json ({len(raw)} bytes JSON -> {n} bytes LZMA) */")
    lines.append("#ifndef VIAL_DEFINITION_H")
    lines.append("#define VIAL_DEFINITION_H")
    lines.append("")
    lines.append(f"#define VIAL_DEFINITION_LEN {n}")
    lines.append("__code uint8_t keyboard_definition[] = {")
    # Emit 16 bytes per line
    for i in range(0, n, 16):
        chunk = data[i:i + 16]
        hexes = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hexes},")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    out = "\n".join(lines) + "\n"
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"Generated {OUT_PATH}: {n} bytes LZMA from {len(raw)} bytes JSON")


if __name__ == "__main__":
    sys.exit(main())
